# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ironbuckets-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect # Adjust to your secret store
  target:
    name: ironbuckets-secret
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: ironbuckets
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: ironbuckets
        property: MINIO_SECRET_KEY
